[2021-12-01 11:24:04,388] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_sample_dag.run_this_first manual__2021-12-01T11:24:04.044057+00:00 [queued]>
[2021-12-01 11:24:04,401] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_sample_dag.run_this_first manual__2021-12-01T11:24:04.044057+00:00 [queued]>
[2021-12-01 11:24:04,402] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-01 11:24:04,402] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-01 11:24:04,402] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-01 11:24:04,419] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): run_this_first> on 2021-12-01 11:24:04.044057+00:00
[2021-12-01 11:24:04,424] {standard_task_runner.py:52} INFO - Started process 286 to run task
[2021-12-01 11:24:04,428] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'run_this_first', 'manual__2021-12-01T11:24:04.044057+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp5slwjd9f', '--error-file', '/tmp/tmpxoyovj_o']
[2021-12-01 11:24:04,429] {standard_task_runner.py:77} INFO - Job 15: Subtask run_this_first
[2021-12-01 11:24:04,464] {logging_mixin.py:109} INFO - Running <TaskInstance: my_sample_dag.run_this_first manual__2021-12-01T11:24:04.044057+00:00 [running]> on host e0158a46c8db
[2021-12-01 11:24:04,508] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pipis
AIRFLOW_CTX_DAG_ID=my_sample_dag
AIRFLOW_CTX_TASK_ID=run_this_first
AIRFLOW_CTX_EXECUTION_DATE=2021-12-01T11:24:04.044057+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-01T11:24:04.044057+00:00
[2021-12-01 11:24:04,509] {logging_mixin.py:109} INFO - I am coming first
[2021-12-01 11:24:04,509] {python.py:152} INFO - Done. Returned value was: None
[2021-12-01 11:24:04,520] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_sample_dag, task_id=run_this_first, execution_date=20211201T112404, start_date=20211201T112404, end_date=20211201T112404
[2021-12-01 11:24:04,560] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-01 11:24:04,591] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
