[2021-12-01 16:46:42,160] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: FrequencyCount.map3 manual__2021-12-01T14:50:52.095578+00:00 [queued]>
[2021-12-01 16:46:42,174] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: FrequencyCount.map3 manual__2021-12-01T14:50:52.095578+00:00 [queued]>
[2021-12-01 16:46:42,174] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-01 16:46:42,174] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-12-01 16:46:42,174] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-01 16:46:42,185] {taskinstance.py:1262} INFO - Executing <Task(MapOperator): map3> on 2021-12-01 14:50:52.095578+00:00
[2021-12-01 16:46:42,190] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2021-12-01 16:46:42,193] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FrequencyCount', 'map3', 'manual__2021-12-01T14:50:52.095578+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/mapred.py', '--cfg-path', '/tmp/tmpy410wk6a', '--error-file', '/tmp/tmprjbyfe2s']
[2021-12-01 16:46:42,194] {standard_task_runner.py:77} INFO - Job 58: Subtask map3
[2021-12-01 16:46:42,226] {logging_mixin.py:109} INFO - Running <TaskInstance: FrequencyCount.map3 manual__2021-12-01T14:50:52.095578+00:00 [running]> on host 60ba21408f08
[2021-12-01 16:46:42,272] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FrequencyCount
AIRFLOW_CTX_TASK_ID=map3
AIRFLOW_CTX_EXECUTION_DATE=2021-12-01T14:50:52.095578+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-01T14:50:52.095578+00:00
[2021-12-01 16:46:42,499] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=FrequencyCount, task_id=map3, execution_date=20211201T145052, start_date=20211201T164642, end_date=20211201T164642
[2021-12-01 16:46:42,526] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-01 16:46:42,577] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
